export default {
    RADIO_SELECTED: 'tick_round_filled',
    RADIO_UNSELECTED: 'circle_outlined',
    ADD: 'add',
    ADD_ROUND_OUTLINED: 'add_rounded_outlined',
    ADD_ROUND_FILLED: 'add_rounded_filled',
    ADD_RECT_OUTLINED: 'add_rect_outlined',
    DELETE: 'bin',
    EDIT: 'pencil',
    BACK: 'backward_head',
    FORWARD: 'forward_head',
    UP: 'up_head',
    DOWN: 'down_head',
    UP_HEAD_FILLED: 'up_head_filled', //
    DOWN_HEAD_FILLED: 'down_head_filled',
    ARROW_HEAD_FILLED: 'arrow_head_filled',
    UP_ARROW: 'up_arrow', //
    UP_ARROW_ROUND_FILLED: 'up_arrow_round_filled',
    DOWN_ARROW: 'down_arrow',
    DOWN_ARROW_ROUND_FILLED: 'down_arrow_round_filled',
    TICK_ROUND_FILLED: 'tick_round_filled',
    REFRESH: 'circular_arrow',
    ARROW_DOWN_FILLED: 'arrow_down_filled',
    CLOSE: 'cross',
    TICK_SQUARE_FILLED: 'tick_square_filled',
    HORIZONTAL_LINE: 'horizontal_line',
    SQUARE_OUTLINED: 'square_outlined',
    RECTANGLE_FILLED: 'rectangle_filled',
    CIRCLE_FILLED: 'circle_filled',
    CIRCLE_OUTLINED: 'circle_outlined',
    ARROW_UP_W_LINE: 'arrow_up_w_line',
    ARROW_DOWN_W_LINE: 'arrow_down_w_line',
    ARROW_BACK_W_LINE: 'arrow_back_w_line',
    ARROW_FORWARD_W_LINE: 'arrow_forward_w_line',
  
    TICK: 'tick',
    MESSAGE_FILLED: 'message_filled',
    LOCK_FILLED: 'lock_filled',
    KEY_OUTLINED_FILLED: 'key_outlined_filled',
    VIDEO_ROUND_FILLED: 'video_round_filled',
    HELP: 'help',
    TICKET: 'ticket',
    MOON_CRESCENT_OUTLINED_FILLED: 'moon_crescent_outlined_filled',
    SUN: 'sun',
    MOON_CRESCENT_FILLED: 'moon_crescent_filled',
    MOON_CRESCENT: 'moon_crescent',
    CLOSE_FILLED: 'cross_filled',
    OFFER: 'percent_round_filled',
    SORT: 'up_down_head_filled',
  
    CREATE_STRATEGY: 'bulb',
    CREATE_BASKET: 'basket',
    CONVERT_INTO_STRATEGY: 'ring_square_loop',
  
    // -------- ORDERBOOK TAGS ICONS ----------
    OPEN: 'circle_filled_outlined',
    CANCEL: 'cancel_filled',
    REJECTED: 'rejected_filled',
    TRIGGER_PENDING: 'clock_filled_outlined',
    // -------- ORDERBOOK TAGS ICONS ----------
  
    BULLISH: 'bullish_head',
    BEARISH: 'bearish_head',
    NEUTRAL: 'neutral',
  
    CHART_CANDLESTICK: 'candlestick',
    CHART_HEIKIN_ASHI: 'heikin_ashi',
  
    POSITION: 'flag_round_filled',
    ENTRY: 'entry_rounded_filled',
    EXIT: 'exit_rounded_filled',
    PARAMETERS: 'parameters',
  
    LIST_VIEW: 'two_horizontal_line',
    GRID_VIEW: 'four_square_filled',
    THREE_DOTS_HORIZONTAL: 'meatball',
    THREE_DOTS_VERTICAL: 'kebab',
  
    LIKE: 'thumbs_up',
    DISLIKE: 'thumbs_down',
    SEARCH: 'search',
    CALENDAR: 'calendar',
    MINUS: 'minus',
    VIEW: 'eye',
    COPY: 'copy',
    SHARE: 'share',
    LINK: 'link',
    WARN: 'exclamation_round_filled',
    EMBED_CODE: 'embed_code',
    DOWNLOAD_OUTLINED: 'download_outlined',
    SCAN_ROUND_FILLED: 'scan_round_filled',
    SCAN: 'scan',
    IMAGE: 'image',
    EARTH_W_CLOCK: 'earth_w_clock',
    COPY_FILLED: 'copy_filled',
    // FILTER: 'funnel',
    FILTER: 'filter',
    SETTING_OUTLINED: 'setting_outlined',
    TWO_GEAR: 'two_gear',
    SETTING: 'setting',
    CALENDER: 'calender',
    SPARKLINE: 'sparkline',
    UN_FAVOURITE: 'star_outlined',
    FAVOURITE: 'star_filled',
    CAMERA_ROUND_FILLED: 'camera_round_filled',
    SPEEDOMETER: 'speedometer',
    LOCK: 'lock',
    CLOCK: 'clock',
    COMMODITY: 'commodity_round_filled',
    EQUITY: 'equity_round_filled',
    EMAIL: 'email',
    PHONE: 'phone',
    ID_CARD: 'id_card',
    UNSUBSCRIBE: 'cross_w_pointer',
    CAMERA: 'camera',
    PRICING: 'pricing',
    PROFILE: 'profile',
    BILLING: 'billing',
  
    // NOTIFICATION
    NOTIF_DEFAULT: 'robot',
    NOTIF_AUTO: 'wifi',
    NOTIF_PAPER: 'paper',
    NOTIF_SCANNER: 'scanner_duo',
    PAPER: 'paper',
    NOTIFICATION: 'notification',
    AUTO: 'robot',
    AUTO_FILLED: 'robot_round_filled',
}


// "message_round_filled","lock_round_filled","billing","pricing","profile","tick","key_outlined_filled","video_round_filled","help","ticket","moon_crescent_outlined_filled","sun","moon_crescent_filled","arrow_back_w_linesvg","arrow_forward_w_line","cross_w_pointer","bulb","basket","ring_square_loop","circle_filled_outlined","cancel_filled","rejected_filled","clock_filled_outlined","all","mean_reversion","miscellaneous","momentum","overlays","pivot_points","price_action","trend_following","up_down_head_filled","filter","parachute_round_filled","cross_filled_outlined","no_action_round_filled","paper_round_filled","robot_round_filled","right_arrow_w_line_round_filled","cart_round_filled","clock_expired_filled_outlined","radar_round_filled","cross_filled","equity_round_filled","commodity_round_filled","percent_round_filled","email","id_card","phone","candlestick_filled","youtube_filled","bearish_head_filled","bullish_head_filled","crossover","bearish_head_filled_outlined","bullish_head_filled_outlined","range_breakout","top_gainers","top_losers","add_rect_outlined","add_rounded_filled","add_rounded_outlined","add","arrow_down_filled","arrow_down_w_line","arrow_up_w_line","download_outlined","arrow_left_w_square","Asset-157","basket_round_filled","bearish_head","bell_round_filled","bell_tilted","bell","bin","bullish_head","calender","camera_round_filled","camera","candlestick","circle_filled","circle_outlined","circular_arrow","clock_filled","clock","copy_filled","copy","cross","double_arrow_horizontal_filled","down_head_filled","earth_w_clock","embed_code","exit_rounded_filled","entry_rounded_filled","up_arrow_round_filled","down_arrow_round_filled","exclamation_round_filled","eye","flag_round_filled","four_square_filled","funnel","heikin_ashi","horizontal_line_tick","horizontal_line","image","kebab","letter_b","letter_n","letter_s","link","lock","meatball","minus","moon_crescent","neutral","parameters","pencil","pointer_round_filled","radio_selected","rectangle_filled","rocket_tilted","rocket_outlined","scan_round_filled","scan","search","setting_outlined","setting","share","sparkline","speedometer","square_outlined","star_filled","star_outlined","stop_round_filled","tab_add","tab_create","tab_home","tab_market","tab_profile","three_cards","thumbs_down","thumbs_up","tick_round_filled","tick_square_filled","two_gear","two_horizontal_line","backward_head","forward_head","down_head","up_head","up_arrow","down_arrow","up_head_filled","arrow_head_filled","wifi","robot","paper"